### ISSUE TITLE
Não precisa manter uma referencia para cada lista

### ISSUE THREAD

**Issue by juliocbcotta** [Undeon/QualAbastecer#1]
https://github.com/Undeon/QualAbastecer/blob/master/app/src/main/java/com/danielfonseca/qualabastecer/Veiculos/CadastrarVeiculosActivity.kt#L25

vc pode simplesmente criar a lista localmente no onResponse e não precisa de adicionar items nas listas já existentes.

**Comment by Undeon** [comment]
Resolvido com a ultima atualização.
