### ISSUE TITLE
a configuração dos adapters está fragmentada

### ISSUE THREAD

**Issue by juliocbcotta** [Undeon/QualAbastecer#3]
https://github.com/Undeon/QualAbastecer/blob/master/app/src/main/java/com/danielfonseca/qualabastecer/Veiculos/CadastrarVeiculosActivity.kt#L135

parte da configuração está no método adapterAno () e o restante em onResponse.. que tal colocar tudo no mesmo método passando como parametro a lista de objetos?

**Comment by Undeon** [comment]
Resolvido com a ultima atualização.
