### ISSUE TITLE
passar parametros para métodos

### ISSUE THREAD

**Issue by juliocbcotta** [Undeon/QualAbastecer#4]
https://github.com/Undeon/QualAbastecer/blob/master/app/src/main/java/com/danielfonseca/qualabastecer/Veiculos/CadastrarVeiculosActivity.kt#L124

que tal passar os valores para o método ? Isso evita a necessidade de manter esses valores como propriedades.

**Comment by Undeon** [comment]
Resolvido com a ultima atualização.
