### ISSUE TITLE
Tratamento de erro

### ISSUE THREAD

**Issue by juliocbcotta** [Undeon/QualAbastecer#7]
https://github.com/Undeon/QualAbastecer/blob/master/app/src/main/java/com/danielfonseca/qualabastecer/Veiculos/CadastrarVeiculosActivity.kt#L80

Que tal adicionar um tratamento de erro? Um alerta falando que a requisição falhou e com um botão "Tentar novamente"?

**Comment by Undeon** [comment]
Resolvido com a ultima atualização.
